name: pyxpcm-streamlit
channels:
  - conda-forge
dependencies:
  - python = 3.8

# CORE:
  - aiohttp = 3.8.4
  - erddapy = 2.0.1
  - fsspec = 2023.5.0
  - netCDF4 = 1.6.3
  - packaging = 23.1
  - scipy = 1.10.1
  - toolz = 0.12.0
  - xarray = 2023.1.0
  - plotly = 5.9.0
  - watchdog = 2.1.6
  - argopy = 0.1.15

# EXT.UTIL:
  - gsw = 3.6.16
  - tqdm = 4.65.0
  - zarr = 2.14.2

# EXT.PERF:
  - dask = 2023.5.0
  - distributed = 2023.5.0
  - pyarrow = 12.0.0

# EXT.PLOT:
  - IPython = 8.12.2
  - cartopy = 0.21.1
  - ipykernel = 6.23.1
  - ipywidgets = 8.0.6
  - matplotlib = 3.7.1
  - seaborn = 0.12.2

# DEV:
  - bottleneck = 1.3.7
  - cfgrib = 0.9.10.4
  - cftime = 1.6.2
  - numpy = 1.24.3
  - pandas = 1.5.3

# PIP
  - pip = 23.2.1
  - pip:
      - streamlit==1.26
      - git+https://github.com/obidam/pyxpcm

