name: pyxpcm-streamlit
channels:
  - conda-forge
dependencies:
  - python = 3.8

# CORE:
  - argopy = 0.1.15
  - aiohttp
  - erddapy
  - fsspec
  - netCDF4
  - packaging
  - scipy
  - toolz
  - xarray
  - plotly
  - watchdog
  - folium
  - streamlit-folium

# EXT.UTIL:
  - gsw
  - tqdm
  - zarr

# EXT.PERF:
  - dask
  - distributed
  - pyarrow

# EXT.PLOT:
  - IPython
  - cartopy
  - ipykernel
  - ipywidgets
  - matplotlib
  - seaborn

# DEV:
  - bottleneck
  - cfgrib
  - cftime
  - numpy
  - pandas

# PIP
  - pip
  - pip:
      - streamlit
      - git+https://github.com/obidam/pyxpcm

